import type { Lang } from '@/i18n';

import type { Area, Skill } from './types';

type Suggestions = Record<Area, Skill[]>;

const b = (name: string): Skill => ({ name, type: 'comportamental' });
const tec = (name: string): Skill => ({ name, type: 'tecnica' });

/**
 * Sugestões fixas de competências por área (T19), no idioma do app. Mostramos até 4 que a pessoa ainda não tem.
 * Para mudar as sugestões, edite só estas listas (mesma ordem de ideias em todos os idiomas).
 */
export const SKILL_SUGGESTIONS: Record<Lang, Suggestions> = {
  'pt-BR': {
    atendimento: [b('Pontualidade'), tec('Atendimento ao cliente'), b('Resolução de problemas'), tec('Digitação'), b('Paciência'), b('Comunicação')],
    vendas: [b('Negociação'), b('Comunicação'), tec('Metas de vendas'), tec('Operação de caixa'), b('Persistência'), tec('Atendimento ao cliente')],
    administrativo: [b('Organização'), tec('Pacote Office'), tec('Excel básico'), tec('Arquivo de documentos'), b('Atenção aos detalhes'), b('Pontualidade')],
    tecnologia: [tec('Lógica de programação'), tec('Suporte técnico'), b('Vontade de aprender'), b('Resolução de problemas'), tec('HTML e CSS'), b('Trabalho em equipe')],
    marketing: [tec('Redes sociais'), b('Criatividade'), tec('Canva'), tec('Escrita'), b('Comunicação'), b('Organização')],
    logistica: [tec('Controle de estoque'), b('Organização'), b('Pontualidade'), tec('Conferência de mercadorias'), b('Trabalho em equipe'), b('Atenção aos detalhes')],
    saude: [b('Empatia'), tec('Primeiros socorros'), tec('Cuidado com o paciente'), b('Calma sob pressão'), b('Organização'), b('Pontualidade')],
    outra: [b('Comunicação'), b('Trabalho em equipe'), b('Pontualidade'), tec('Pacote Office'), b('Vontade de aprender'), b('Organização')],
  },
  en: {
    atendimento: [b('Punctuality'), tec('Customer service'), b('Problem solving'), tec('Typing'), b('Patience'), b('Communication')],
    vendas: [b('Negotiation'), b('Communication'), tec('Sales targets'), tec('Cash handling'), b('Persistence'), tec('Customer service')],
    administrativo: [b('Organization'), tec('Microsoft Office'), tec('Basic Excel'), tec('Document filing'), b('Attention to detail'), b('Punctuality')],
    tecnologia: [tec('Programming logic'), tec('Technical support'), b('Eagerness to learn'), b('Problem solving'), tec('HTML and CSS'), b('Teamwork')],
    marketing: [tec('Social media'), b('Creativity'), tec('Canva'), tec('Writing'), b('Communication'), b('Organization')],
    logistica: [tec('Inventory control'), b('Organization'), b('Punctuality'), tec('Goods receiving'), b('Teamwork'), b('Attention to detail')],
    saude: [b('Empathy'), tec('First aid'), tec('Patient care'), b('Calm under pressure'), b('Organization'), b('Punctuality')],
    outra: [b('Communication'), b('Teamwork'), b('Punctuality'), tec('Microsoft Office'), b('Eagerness to learn'), b('Organization')],
  },
  es: {
    atendimento: [b('Puntualidad'), tec('Atención al cliente'), b('Resolución de problemas'), tec('Mecanografía'), b('Paciencia'), b('Comunicación')],
    vendas: [b('Negociación'), b('Comunicación'), tec('Objetivos de ventas'), tec('Manejo de caja'), b('Constancia'), tec('Atención al cliente')],
    administrativo: [b('Organización'), tec('Paquete Office'), tec('Excel básico'), tec('Archivo de documentos'), b('Atención al detalle'), b('Puntualidad')],
    tecnologia: [tec('Lógica de programación'), tec('Soporte técnico'), b('Ganas de aprender'), b('Resolución de problemas'), tec('HTML y CSS'), b('Trabajo en equipo')],
    marketing: [tec('Redes sociales'), b('Creatividad'), tec('Canva'), tec('Redacción'), b('Comunicación'), b('Organización')],
    logistica: [tec('Control de inventario'), b('Organización'), b('Puntualidad'), tec('Recepción de mercancías'), b('Trabajo en equipo'), b('Atención al detalle')],
    saude: [b('Empatía'), tec('Primeros auxilios'), tec('Atención al paciente'), b('Calma bajo presión'), b('Organización'), b('Puntualidad')],
    outra: [b('Comunicación'), b('Trabajo en equipo'), b('Puntualidad'), tec('Paquete Office'), b('Ganas de aprender'), b('Organización')],
  },
  fr: {
    atendimento: [b('Ponctualité'), tec('Service client'), b('Résolution de problèmes'), tec('Saisie au clavier'), b('Patience'), b('Communication')],
    vendas: [b('Négociation'), b('Communication'), tec('Objectifs de vente'), tec('Tenue de caisse'), b('Persévérance'), tec('Service client')],
    administrativo: [b('Organisation'), tec('Pack Office'), tec('Excel (bases)'), tec('Classement de documents'), b('Souci du détail'), b('Ponctualité')],
    tecnologia: [tec('Logique de programmation'), tec('Support technique'), b('Envie d’apprendre'), b('Résolution de problèmes'), tec('HTML et CSS'), b('Travail en équipe')],
    marketing: [tec('Réseaux sociaux'), b('Créativité'), tec('Canva'), tec('Rédaction'), b('Communication'), b('Organisation')],
    logistica: [tec('Gestion des stocks'), b('Organisation'), b('Ponctualité'), tec('Contrôle des marchandises'), b('Travail en équipe'), b('Souci du détail')],
    saude: [b('Empathie'), tec('Premiers secours'), tec('Soins aux patients'), b('Calme sous pression'), b('Organisation'), b('Ponctualité')],
    outra: [b('Communication'), b('Travail en équipe'), b('Ponctualité'), tec('Pack Office'), b('Envie d’apprendre'), b('Organisation')],
  },
  de: {
    atendimento: [b('Pünktlichkeit'), tec('Kundenservice'), b('Problemlösung'), tec('Zehnfingerschreiben'), b('Geduld'), b('Kommunikation')],
    vendas: [b('Verhandlungsgeschick'), b('Kommunikation'), tec('Verkaufsziele'), tec('Kassieren'), b('Ausdauer'), tec('Kundenservice')],
    administrativo: [b('Organisation'), tec('MS Office'), tec('Excel-Grundlagen'), tec('Ablage von Dokumenten'), b('Sorgfalt'), b('Pünktlichkeit')],
    tecnologia: [tec('Programmierlogik'), tec('IT-Support'), b('Lernbereitschaft'), b('Problemlösung'), tec('HTML und CSS'), b('Teamfähigkeit')],
    marketing: [tec('Social Media'), b('Kreativität'), tec('Canva'), tec('Texten'), b('Kommunikation'), b('Organisation')],
    logistica: [tec('Lagerverwaltung'), b('Organisation'), b('Pünktlichkeit'), tec('Wareneingangskontrolle'), b('Teamfähigkeit'), b('Sorgfalt')],
    saude: [b('Empathie'), tec('Erste Hilfe'), tec('Patientenbetreuung'), b('Belastbarkeit'), b('Organisation'), b('Pünktlichkeit')],
    outra: [b('Kommunikation'), b('Teamfähigkeit'), b('Pünktlichkeit'), tec('MS Office'), b('Lernbereitschaft'), b('Organisation')],
  },
};

/** Nomes de ferramentas: iguais em todos os idiomas. */
const TOOLS = ['excel', 'word', 'office', 'powerpoint', 'canva', 'photoshop', 'python', 'java', 'html', 'css', 'sql'];

/** Palavras que indicam uma competência técnica (algo que se aprende a fazer), por idioma. */
export const TECHNICAL_HINTS: Record<Lang, string[]> = {
  'pt-BR': [
    ...TOOLS,
    'digitação',
    'informática',
    'computador',
    'programação',
    'inglês',
    'espanhol',
    'caixa',
    'estoque',
    'sistema',
    'planilha',
    'libras',
    'cnh',
    'primeiros socorros',
    'redes sociais',
    'atendimento ao cliente',
    'suporte',
  ],
  en: [
    ...TOOLS,
    'typing',
    'computer',
    'programming',
    'coding',
    'spanish',
    'french',
    'cash',
    'inventory',
    'stock',
    'spreadsheet',
    'sign language',
    "driver's license",
    'first aid',
    'social media',
    'customer service',
    'support',
  ],
  es: [
    ...TOOLS,
    'mecanografía',
    'informática',
    'ordenador',
    'computadora',
    'programación',
    'inglés',
    'caja',
    'inventario',
    'almacén',
    'hoja de cálculo',
    'lengua de signos',
    'carné de conducir',
    'primeros auxilios',
    'redes sociales',
    'atención al cliente',
    'soporte',
  ],
  fr: [
    ...TOOLS,
    'saisie',
    'informatique',
    'ordinateur',
    'programmation',
    'anglais',
    'caisse',
    'stock',
    'tableur',
    'langue des signes',
    'permis',
    'premiers secours',
    'réseaux sociaux',
    'service client',
    'support',
  ],
  de: [
    ...TOOLS,
    'zehnfinger',
    'edv',
    'computer',
    'programmier',
    'englisch',
    'kasse',
    'kassieren',
    'lager',
    'tabellenkalkulation',
    'gebärdensprache',
    'führerschein',
    'erste hilfe',
    'social media',
    'kundenservice',
    'support',
  ],
};

/** Palavras que indicam uma competência comportamental (jeito de agir), por idioma. */
export const BEHAVIORAL_HINTS: Record<Lang, string[]> = {
  'pt-BR': [
    'comunicação',
    'empatia',
    'organização',
    'pontualidade',
    'paciência',
    'equipe',
    'liderança',
    'criatividade',
    'responsabilidade',
    'proatividade',
    'flexibilidade',
    'calma',
    'persistência',
    'negociação',
    'resolução de problemas',
    'vontade de aprender',
    'atenção',
    'dedicação',
    'escuta',
    'educação',
    'respeito',
  ],
  en: [
    'communication',
    'empathy',
    'organization',
    'punctuality',
    'patience',
    'team',
    'leadership',
    'creativity',
    'responsib',
    'initiative',
    'flexibility',
    'calm',
    'persistence',
    'negotiation',
    'problem solving',
    'eager',
    'attention',
    'dedication',
    'listening',
    'politeness',
    'respect',
  ],
  es: [
    'comunicación',
    'empatía',
    'organización',
    'puntualidad',
    'paciencia',
    'equipo',
    'liderazgo',
    'creatividad',
    'responsabilidad',
    'iniciativa',
    'flexibilidad',
    'calma',
    'constancia',
    'negociación',
    'resolución de problemas',
    'ganas de aprender',
    'atención al detalle',
    'dedicación',
    'escucha',
    'educación',
    'respeto',
  ],
  fr: [
    'communication',
    'empathie',
    'organisation',
    'ponctualité',
    'patience',
    'équipe',
    'leadership',
    'créativité',
    'responsabilité',
    'initiative',
    'flexibilité',
    'calme',
    'persévérance',
    'négociation',
    'résolution de problèmes',
    'envie d’apprendre',
    'souci du détail',
    'rigueur',
    'écoute',
    'politesse',
    'respect',
  ],
  de: [
    'kommunikation',
    'empathie',
    'organisation',
    'pünktlichkeit',
    'geduld',
    'team',
    'führung',
    'kreativität',
    'verantwortung',
    'eigeninitiative',
    'flexibilität',
    'ruhe',
    'ausdauer',
    'verhandlung',
    'problemlösung',
    'lernbereitschaft',
    'sorgfalt',
    'belastbarkeit',
    'zuhören',
    'höflichkeit',
    'respekt',
  ],
};
